sonardb-postgres:
  image: postgres:9.5.0
  container_name: sonardb-postgres
  restart: always
  volumes:
    - ./postgresql/data:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: sonarqube
    POSTGRES_PASSWORD: s0n4rqub3
sonarqube:
  image: sonarqube:5.3
  container_name: sonarqube
  restart: always
  ports:
    - "9000:9000"
  volumes:
    - ./extensions:/opt/sonarqube/extensions
    - ./lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  environment:
    SONARQUBE_JDBC_USERNAME: sonarqube
    SONARQUBE_JDBC_PASSWORD: s0n4rqub3
    SONARQUBE_JDBC_URL: jdbc:postgresql://sonardb:5432/sonarqube
  links:
    - sonardb-postgres:sonardb
