server:
  build: ./server
  container_name: ace-server
  restart: always
  ports:
    - "8080:8080"
  stdin_open: true
  tty: true
target:
  build: ./target
  restart: always
  links:
    - "server:ace"
  ports:
    - "8080"
  stdin_open: true
  tty: true
